# Generated by Django 5.0.3 on 2024-03-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.BigIntegerField(default=100000),
        ),
    ]
