# Generated by Django 5.0.3 on 2024-03-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="balance",
            field=models.FloatField(default=100000),
        ),
    ]
