# Generated by Django 5.0.3 on 2024-04-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transactionDate', models.DateField(auto_now_add=True)),
                ('stock', models.CharField(max_length=255)),
                ('isBuyOrder', models.BooleanField(default=True, max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('isActive', models.BooleanField(default=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
