# Generated by Django 5.0.3 on 2024-03-12 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('stockID', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(max_length=255)),
                ('buyingPrice', models.IntegerField(max_length=255)),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
