# Generated by Django 5.0.3 on 2024-03-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_customuser_groups_and_more'),
        ('portfolio', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='buyingPrice',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='isActive',
            field=models.BooleanField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='isBuyOrder',
            field=models.BooleanField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='transaction_date',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
