# Generated by Django 5.0.3 on 2024-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="quantity", field=models.IntegerField(default=0),
        ),
    ]
