# Generated by Django 5.0.3 on 2024-04-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_order_quantity"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="isBuyOrder",),
    ]
