# Generated by Django 5.0.3 on 2024-03-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_portfolio_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='transaction_date',
            new_name='transactionDate',
        ),
    ]
