# Generated by Django 5.0.3 on 2024-03-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_customuser_groups_and_more'),
        ('portfolio', '0005_rename_transaction_date_orders_transactiondate'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
