# Generated by Django 5.0.3 on 2024-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_orders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stockID',
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='transactionDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
