# Generated by Django 5.0.3 on 2024-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transactionDate", models.DateField(auto_now_add=True)),
                ("ticker", models.CharField(max_length=255)),
                ("price", models.FloatField(max_length=255)),
            ],
            options={"unique_together": {("ticker", "price", "transactionDate")},},
        ),
    ]
