# Generated by Django 5.0.3 on 2024-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="price",
            field=models.FloatField(default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(default="", max_length=255),
        ),
    ]
