# Generated by Django 5.0.3 on 2024-04-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_alter_stock_price_alter_stock_ticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="transactionDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
