# Generated by Django 5.0.3 on 2024-04-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_alter_stock_transactiondate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(default=".", max_length=255),
        ),
    ]
