# Generated by Django 5.0.3 on 2024-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_alter_stock_ticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(default="", max_length=255),
        ),
    ]
