# Generated by Django 5.0.3 on 2024-04-08 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0006_alter_stock_transactiondate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="transactionDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 8, 10, 34, 33, 482341)
            ),
        ),
    ]
